# React ビルド用ステージ
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

# ← build args を受け取れるようにする
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY . .
RUN npm run build

# Nginx ステージ
FROM nginx:alpine
# React のビルド成果物をコピー
COPY --from=build /app/dist /usr/share/nginx/html
# nginx.conf をコピー（frontend 配下にある想定）
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]