version: "3.9"

services:
  db:
    image: postgres:15
    container_name: schedule-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: schedule-backend
    env_file: .env
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}   # AlembicやSQLAlchemyが利用
      API_PORT: ${API_PORT}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: schedule-frontend
    env_file: ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${WEB_PORT}:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/public:/app/public
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: