events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    #
    # host → service mapping
    #
    map $host $frontend_upstream {
        stg-sukejuru.yudais-prod.com frontend-stg;
        app-sukejuru.yudais-prod.com frontend-prod;
    }

    map $host $backend_upstream {
        stg-sukejuru.yudais-prod.com backend-stg;
        app-sukejuru.yudais-prod.com backend-prod;
    }

    #
    # HTTP → HTTPS redirect
    #
    server {
        listen 80;
        server_name stg-sukejuru.yudais-prod.com app-sukejuru.yudais-prod.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    #
    # HTTPS reverse proxy
    #
    server {
        listen 443 ssl;
        server_name stg-sukejuru.yudais-prod.com app-sukejuru.yudais-prod.com;

        ssl_certificate     /etc/letsencrypt/live/yudais-prod.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yudais-prod.com/privkey.pem;

        #
        # frontend
        #
        location / {
            proxy_pass http://$frontend_upstream;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #
        # backend API
        #
        location /api/ {
            proxy_pass http://$backend_upstream:8000/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}