events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    resolver 127.0.0.11 valid=10s;
    #
    # HTTP → HTTPS redirect
    #
    server {
        listen 80;
        server_name app-sukejuru.yudais-prod.com stg-sukejuru.yudais-prod.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    #
    # PROD
    #
    server {
        listen 443 ssl;
        server_name app-sukejuru.yudais-prod.com;

        ssl_certificate     /etc/letsencrypt/live/yudais-prod.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yudais-prod.com/privkey.pem;

        location / {
            proxy_pass http://frontend-prod;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ^~ /api/ {
            proxy_pass http://backend-prod:8000/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
    #
    # STG
    #
    server {
        listen 443 ssl;
        server_name stg-sukejuru.yudais-prod.com;

        ssl_certificate     /etc/letsencrypt/live/yudais-prod.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yudais-prod.com/privkey.pem;

        location / {
            proxy_pass http://frontend-stg;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ^~ /api/ {
            proxy_pass http://$backend-stg:8000/;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}