x-common: &common
  env_file: ../../.env.prod
  networks:
    - schedule_app_net
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  backend-prod:
    <<: *common
    working_dir: /app
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    image: schedule_app-backend:latest
    depends_on:
      db-prod:
        condition: service_healthy

  frontend-prod:
    <<: *common
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api
    image: schedule_app-frontend:latest
    depends_on:
      - backend-prod
  db-prod:
    <<: *common
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:

networks:
  schedule_app_net:
    external: true
