x-common: &common
  env_file: ../../.env
  networks:
    - schedule_app_net
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  backend-stg:
    <<: *common
    working_dir: /app
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    image: schedule_app-backend-stg:latest
    environment:
      - RP_ID=stg-sukejuru.yudais-prod.com
      - ORIGIN=https://stg-sukejuru.yudais-prod.com:8443
    depends_on:
      db-stg:
        condition: service_healthy
  frontend-stg:
    <<: *common
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api
    image: schedule_app-frontend-stg:latest
    depends_on:
      - backend-stg

  db-stg:
    <<: *common
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data_stg:/var/lib/postgresql/data

volumes:
  postgres_data_stg:

networks:
  schedule_app_net:
    external: true
