"""update passkey defaults and constraints

Revision ID: 0cc34c85b163
Revises: 684db21276ce
Create Date: 2026-02-14 03:41:43.695625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cc34c85b163'
down_revision: Union[str, Sequence[str], None] = '684db21276ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passkeys', 'public_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('passkeys', 'sign_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('passkeys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passkeys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('passkeys', 'sign_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('passkeys', 'public_key',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
