"""add unique to challenges.user_id

Revision ID: 684db21276ce
Revises: a97c1c47bb61
Create Date: 2026-02-14 02:44:25.829549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684db21276ce'
down_revision: Union[str, Sequence[str], None] = 'a97c1c47bb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'challenges', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='unique')
    # ### end Alembic commands ###
